### PR TITLE
fix drains call with paranoid apps

### PR DESCRIPTION
**Pull request by dickeyxxx**

### CODE REVIEW

**Comment by ransombriggs** [comment]
@dickeyxxx the code looks fine, though I am not sure how it fixes the paranoid issues, I guess I was expecting to see a preAuth: true or something

**Comment by dickeyxxx** [comment]
I'm not sure either. I'll check

**Comment by dickeyxxx** [comment]
looking at this again. @ransombriggs it fixes it because it turns it into 1 request rather than N+1

**Comment by ransombriggs** [comment]
@dickeyxxx my other 2fa fix also fixed this issue with drains, do you still want to merge this code?

**Comment by dickeyxxx** [comment]
Meh

**Pull request closed without merging**
