### PR TITLE
Fix bug that prevents running `heroku create --app blah --org financial-times` in some cases

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by dickeyxxx** [comment]
This shouldn't be necessary since the plugin specifies `wantsOrg: true`. If that flag isn't displaying it is likely that the Go portion of the code is out of date. Try ensuring the CLI is updated before running the create command by calling `heroku update` before running any code.

**Comment by dickeyxxx** [comment]
actually I might have been able to repro this, hang on

**Comment by phamann** [comment]
We have also repo'ed this and adding this line resolves our issue.

**Comment by dickeyxxx** [comment]
OK this is actually a caching issue, if you run `heroku plugins:install heroku-apps` it will clear the cache for the plugin and fix itself. I'll have to come up with a better strategy for the caching.

**Comment by dickeyxxx** [comment]
This isn't a real fix since it would break compatibility with the `HEROKU_ORGANIZATION` env var that some users use. I can't merge this.

**Comment by phamann** [comment]
Ok we will give that a go. Thank you.

**Comment by phamann** [comment]
I can confirm that adding `heroku plugins:install heroku-apps` as a pre-build step resolved this issue. 

Thank you for your help.

**Comment by matthew-andrews** [comment]
Thanks @dickeyxxx !

**Comment by dickeyxxx** [comment]
glad to hear the workaround fixed it. I'm going to get a better solution here to either ensure it's cached or to not use the cache in some cases to prevent this from happening again.

**Comment by dickeyxxx** [comment]
FYI this is a potential fix for the problem: https://github.com/heroku/heroku-cli/pull/170

Not sure if it makes a ton of sense. Essentially it's that updates could get stuck using old code to cache the plugin metadata. I can elaborate more if you'd like.

**Comment by matthew-andrews** [comment]
i think i sort of understand.  thanks!  by removing our workaround i can still reliably reproduce the bug so if you'd like to ping me when that's shipped i will be able to confirm that it's fixed if that's useful?

sorry that you had to get woken up this morning! :sunrise:

**Comment by matthew-andrews** [comment]
> by removing our workaround i can still reliably reproduce the bug
Oops not yet confirm this yet

**Comment by dickeyxxx** [comment]
Mind trying again? Fix is out.

**Comment by dickeyxxx** [comment]
hmm it seems circle still uses the old version for the updates. Even though I put out a fix that it updates to, it wouldn't be run. We probably need to get them to run `rm ~/.heroku` on their image. That would also fix your problem, but it would be a bit slower than just reinstalling the plugin.

**Comment by dickeyxxx** [comment]
I've opened up a support ticket with Circle to get it fixed in the image.

**Comment by matthew-andrews** [comment]
I think you know this already but I re-ran one of our builds without the work around and it is indeed still broken…

**Comment by dickeyxxx** [comment]
I spoke with circle, they need to do a re-image in order to fix it. They weren't sure when that would happen.

**Comment by dickeyxxx** [comment]
If you'd like to see it fixed, I would open up a support ticket with them as well.

**Pull request closed without merging**
