### PR TITLE
Use API V3 in releases info

### LINKED ISSUE #147: Using a deprecated V2 Endpoint
Creating this issue to track the change.

Release info [uses a v2 endpoint to get a particular release's env vars](https://github.com/heroku/heroku-apps/blob/master/commands/releases/info.js#L33).

We now have a [v3 endpoint](https://devcenter.heroku.com/articles/platform-api-reference#config-vars-info-for-app-release) to support this.

/cc @dmathieu

### PR DESCRIPTION
**Pull request by dmathieu**
Closes #147

cc @heroku/build @dickeyxxx @ransombriggs @dmcinnes

### CODE REVIEW

**Comment by dmcinnes** [comment]
🎉  Sweet!

**Comment by tt** [comment]
@dmcinnes, can we do a breakdown per endpoint to inform how we might still be using V2?

**Comment by dmcinnes** [comment]
@tt most of what I've been aware of came from @dickeyxxx in this API ticket https://github.com/heroku/api/issues/6287

Doing some splunking the only other command I see (from up-to-date clients) is [`ps:stop`](https://github.com/heroku/heroku-apps/blob/master/commands/ps/stop.js). 
I'll create a ticket for that one.

**Comment by dmcinnes** [comment]
Created #149 for `ps:stop`

**Comment by dickeyxxx** [comment]
lgtm

**Pull request merged**
